export const WHATSAPP_NUMBER = "6287801351421";
export const EMAIL = "jiddanarmansyiah@gmail.com";
export const LINKEDIN = "https://www.linkedin.com/in/jiddanarmansiyah/";
export const GITHUB = "https://github.com/FourGiraffe4028";
export const LOCATION = "Jawa Barat, Indonesia";
// Kosong / tidak diset -> same-origin "/api" (mis. saat deploy di Vercel).
export const API_URL = `${process.env.REACT_APP_BACKEND_URL || ""}/api`;

export const NAV_IDS = ["home", "about", "education", "experience", "organization", "skills", "portfolio", "achievements", "contact"];

export const content = {
  preloader: { tagline: "Menghadirkan solusi teknologi informasi & infrastruktur digital…" },
  nav: { home: "Beranda", about: "Tentang", education: "Pendidikan", experience: "Pengalaman", organization: "Organisasi", skills: "Kemampuan", portfolio: "Portofolio", achievements: "Prestasi", contact: "Kontak" },
  hero: {
    greeting: "Halo, saya",
    name: "Mochammad Jiddan Armansyiah",
    roles: ["Manajemen Informatika", "IT Support", "Web Developer", "Network Administrator"],
    sub: "Mahasiswa Manajemen Informatika (D3) Politeknik LP3I Jakarta yang adaptif dan terorganisir, dengan minat dan keahlian di bidang IT Support, Web Development, Jaringan Komputer, dan Hardware Enthusiast.",
    viewWork: "Lihat Project Saya Dikembangkan",
    downloadCv: "Unduh CV",
    scroll: "Gulir Kebawah :)",
    portraitAlt: "Potret Mochammad Jiddan Armansyiah (JA)",
    portraitNote: "Foto profesional segera hadir",
    cards: [
      { icon: "grad", title: "Lulus 2027", sub: "Politeknik LP3I Jakarta" },
      { icon: "globe", title: "Lulus 2024", sub: "SMK Tel. Telesandi Bekasi" },
      { icon: "star", title: "IPK 3,69 / 4,00", sub: "Manajemen Informatika" },
    ],
  },
  about: {
    num: "01", title: "Tentang Saya", sub: "Jembatan antara teknologi, sistem informasi, dan solusi digital.",
    paragraphs: [
      "Saya adalah mahasiswa jurusan Manajemen Informatika dari Politeknik LP3I Jakarta yang adaptif, terorganisir, dan memiliki antusiasme tinggi terhadap perkembangan teknologi baru.",
      "Memiliki kemampuan perencanaan yang kuat serta terbiasa berkolaborasi dalam tim untuk menyelesaikan proyek secara efektif. Didukung pengalaman praktis di bidang IT Support, instalasi & konfigurasi jaringan komputer, perakitan hardware, serta pengembangan aplikasi berbasis web.",
      "Saya siap berkontribusi positif dan profesional dalam lingkungan kerja yang dinamis untuk mendukung keandalan sistem informasi dan infrastruktur TI.",
    ],
    infoTitle: "Sekilas tentang saya",
    info: [
      { k: "Nama", v: "Mochammad Jiddan Armansyiah" },
      { k: "Program Studi", v: "Manajemen Informatika" },
      { k: "Universitas", v: "Politeknik LP3I Jakarta" },
      { k: "Domisili", v: "Bekasi, Jawa Barat, Indonesia" },
    ],

    photoCaption: "Foto Saya ketika di sebuah kafe di galaxy",
    photoNote: "Foto segera hadir",
  },
  education: {
    num: "02", title: "Pendidikan", sub: "Fondasi di bidang manajemen informatika, teknik komputer jaringan, dan teknologi digital.",
    items: [
      {
        school: "Politeknik LP3I Jakarta", location: "Jakarta, Indonesia", period: "2024 – 2027",
        degree: "Manajemen Informatika", extra: "IPK 3,69 / 4,00",
        image: "/assets/lp3i-jakarta.png",
        bullets: [
          "Studi perancangan sistem informasi, algoritma pemrograman, dan pengembangan aplikasi berbasis web & basis data.",
          "Praktik pengelolaan basis data relasional (SQL), perancangan antarmuka aplikasi, serta integrasi sistem informasi bisnis.",
          "Konfigurasi dan pemeliharaan infrastruktur TI, administrasi jaringan komputer, serta penanganan troubleshooting perangkat keras dan lunak.",
        ],
        tags: ["Manajemen Informatika", "Web Development", "Database Management", "IT Support", "Jaringan Komputer", "Troubleshooting"],
        note: "Program Diploma III (D3) Manajemen Informatika — Fokus pada Solusi Digital & Infrastruktur TI.",
      },
      {
        school: "SMK Telekomunikasi Telesandi Bekasi", location: "Bekasi, Jawa Barat", period: "2021 – 2024",
        degree: "Teknik Komputer dan Jaringan", extra: "Lulus 2024",
        image: "/assets/smk-telesandi.png",
        bullets: [
          "Konfigurasi dan pemeliharaan arsitektur jaringan komputer lokal (LAN) maupun Wide Area Network (WAN).",
          "Praktik instalasi perangkat jaringan, routing & switching MikroTik dan Cisco, serta manajemen bandwidth.",
          "Perakitan PC, instalasi sistem operasi workstation/server, pengujian kabel jaringan (UTP & Fiber Optic), serta troubleshooting sistem komputer.",
        ],
        tags: ["Teknik Komputer & Jaringan", "MikroTik", "Cisco Routing & Switching", "Instalasi Jaringan LAN/WAN", "Perakitan PC & Server"],
      },
      {
        school: "SMPIT Mutiara Hikmah", location: "Bekasi, Jawa Barat", period: "2018 – 2021",
        degree: "Pendidikan Sekolah Menengah Pertama", extra: "Lulus 2021",
        image: "/assets/smpit-mutiara-hikmah.jpg",
        bullets: [
          "Menyelesaikan jenjang pendidikan menengah pertama dengan fondasi akademik yang kuat dan pembentukan karakter disiplin.",
          "Mempelajari dasar-dasar teknologi informasi, pengenalan aplikasi komputer, serta aktif dalam kegiatan kepemimpinan dan organisasi sekolah.",
        ],
        tags: ["Pendidikan Menengah Pertama", "Dasar Komputer & TI", "Pengembangan Karakter"],
      },
    ],
  },
  experience: {
    num: "03", title: "Pengalaman Magang", sub: "Pengalaman praktis di bidang IT support, konfigurasi jaringan, dan pemeliharaan infrastruktur komputer.",
    items: [
      {
        company: "Politeknik LP3I Jakarta Pusat", location: "Jakarta Pusat", role: "IT Support", period: "November 2025 – Mei 2026", featured: true,
        icon: "laptop",
        desc: "Bertanggung jawab atas dukungan teknis harian bagi staf dan civitas akademika, instalasi dan pemeliharaan jaringan lokal (LAN), troubleshooting hardware dan software, serta pengelolaan fasilitas laboratorium komputer.",
        tasks: [
          "Bagian IT Support",
          "Instalasi Jaringan Komputer",
          "Troubleshooting software dan hardware",
          "Mengelola dan melakukan pemeliharaan fasilitas laboratorium komputer",
        ],
        tags: ["IT Support", "Instalasi Jaringan", "Troubleshooting", "Hardware & Software", "Lab Komputer"],
      },
      {
        company: "Pusdatin Kemendikdasmen", location: "Jakarta", role: "Subkoordinator Infrastruktur", period: "Januari – Maret 2022", featured: false,
        icon: "network",
        desc: "Mendukung divisi infrastruktur teknologi informasi Pusat Data dan Informasi (Pusdatin) dalam pelaksanaan konfigurasi jaringan komputer serta peninjauan dan evaluasi dokumen teknis.",
        tasks: [
          "Bagian Subkoordinator Infrastruktur",
          "Melakukan kegiatan Konfigurasi Jaringan",
          "Melakukan peninjauan dokumen",
        ],
        tags: ["Pusdatin", "Infrastruktur Jaringan", "Konfigurasi Jaringan", "Peninjauan Dokumen"],
      },
    ],
  },
  org: {
    num: "04", title: "Pengalaman Organisasi", sub: "Kepemimpinan di komunitas teknologi, pembinaan anggota, dan penyelenggaraan workshop IT.",
    tabs: [
      { id: "all", label: "Semua" },
      { id: "gallery", label: "Dokumentasi Foto Kegiatan" },
      { id: "leadership", label: "Peran & Tanggung Jawab" },
    ],
    club: {
      name: "LP3I Computer Club (LCC)",
      shortName: "LCC",
      role: "Ketua Umum",
      period: "2025 – Sekarang",
      campus: "Politeknik LP3I Jakarta",
      desc: "Memimpin LP3I Computer Club (LCC) sebagai wadah eksplorasi teknologi, pelatihan praktis, dan kolaborasi bagi mahasiswa dalam bidang IT support, sistem operasi Linux, jaringan komputer, perakitan hardware, dan pengembangan perangkat lunak.",
      highlights: [
        { label: "Organisasi", val: "LP3I Computer Club (LCC)" },
        { label: "Jabatan", val: "Ketua Umum" },
        { label: "Institusi", val: "Politeknik LP3I Jakarta" },
        { label: "Periode", val: "2025 – Sekarang" },
      ],
      tags: ["Ketua Umum", "LP3I Computer Club", "Linux & Open Source", "Troubleshooting PC", "Workshop Daring & Luring"],
    },
    roles: [
      {
        icon: "shield",
        title: "Kepemimpinan & Tata Kelola Organisasi",
        period: "2024 – Sekarang",
        desc: "Mengoordinasikan struktur kepengurusan, memimpin rapat kerja rutin, merancang arah kebijakan komunitas, serta menjaga keharmonisan dan keaktifan seluruh anggota LCC.",
      },
      {
        icon: "terminal",
        title: "Instruktur Workshop & Pemateri Pelatihan",
        period: "2025 – Sekarang",
        desc: "Menginisiasi dan menjadi pemateri pada workshop teknologi, termasuk sesi pengenalan sistem operasi Linux (Debian 11) di VMware Workstation dan manajemen perangkat lunak.",
      },
      {
        icon: "users",
        title: "Mentoring Teknis & Pendampingan 1-on-1",
        period: "2025 – Sekarang",
        desc: "Memberikan bimbingan langsung kepada anggota di lab komputer terkait diagnosa hardware, instalasi tools praktikum, serta problem solving kendala teknis.",
      },
      {
        icon: "cpu",
        title: "Pengelolaan Lab & Kegiatan Praktik TI",
        period: "2025 – Sekarang",
        desc: "Memfasilitasi sesi praktik komputer tatap muka di lab, memastikan kesiapan perangkat kerja, serta mendorong anggota untuk aktif bereksplorasi di bidang teknologi.",
      },
    ],
    gallery: [
      {
        id: "classroom",
        title: "Pertemuan Anggota & Workshop di Lab Komputer",
        tag: "Workshop Tatap Muka",
        image: "/assets/lcc/lcc-classroom.jpg",
        desc: "Memimpin sesi perkumpulan rutin dan pemaparan materi di hadapan seluruh anggota LP3I Computer Club di laboratorium komputer kampus.",
      },
      {
        id: "mentoring",
        title: "Mentoring Teknis & Bimbingan Praktik 1-on-1",
        tag: "Mentoring Anggota",
        image: "/assets/lcc/lcc-mentoring.jpg",
        desc: "Membimbing anggota secara langsung dalam konfigurasi laptop/PC, diagnosa perangkat keras, dan penyelesaian tugas-tugas praktikum TI.",
      },
      {
        id: "webinar-linux",
        title: "Pemateri Daring: Pengenalan Linux & Debian 11",
        tag: "Sesi Google Meet",
        image: "/assets/lcc/lcc-webinar-linux.jpg",
        desc: "Menjadi pemateri utama dalam sesi daring Google Meet 'Pengenalan Linux' dan instalasi Debian 11 pada VMware Workstation untuk anggota LCC.",
      },
      {
        id: "presentation",
        title: "Presentasi Visi & Evaluasi Program Kerja LCC",
        tag: "Kepemimpinan Organisasi",
        image: "/assets/lcc/lcc-presentation.jpg",
        desc: "Mempresentasikan arah program kerja, materi pengembangan komunitas, dan evaluasi kegiatan club di depan proyektor kepada anggota.",
      },
    ],
  },
  skills: {
    num: "05",
    title: "Kemampuan",
    sub: "Kompetensi teknis dan keterampilan interpersonal untuk mendukung solusi TI yang andal dan terstruktur.",
    hardTitle: "Hard Skill",
    softTitle: "Soft Skill",
    hardSkills: [
      "Server & Network Administration",
      "Network Management",
      "Web Development (CodeIgniter 4)",
      "Microsoft Office",
      "PC Assembly & Troubleshooting",
      "Digital Photo & Video Editing",
      "Tenaga Operasi Komputer",
    ],
    softSkills: [
      "Kreativitas",
      "Kemampuan TeamWork dalam Tim",
      "Kemampuan Pemecahan Masalah",
      "Kemampuan Beradaptasi",
    ],
  },
  portfolio: {
    num: "06",
    title: "Portofolio",
    sub: "Dokumentasi proyek teknologi, UI/UX design, sistem IoT, dan implementasi hardware.",
    filters: [
      { id: "all", label: "Semua" },
      { id: "web", label: "Web Development" },
      { id: "uiux", label: "UI/UX Design" },
      { id: "iot", label: "IoT & Smart System" },
      { id: "hardware", label: "Hardware & PC" },
    ],
    viewDetails: "Lihat Detail",
    closeLabel: "Tutup",
    modalLabels: { background: "Tujuan Proyek", role: "Spesifikasi & Implementasi", outcome: "Hasil & Performa", deliverable: "Status" },
    pending: "Berhasil dirakit, diuji, dan aktif beroperasi",
    items: [
      {
        id: "orange-pi-5",
        cat: "hardware",
        title: "Membuat Mini PC dengan Orange Pi 5",
        desc: "Mini PC hemat daya berbasis SoC RockChip RK3588S (ARM 8nm), RAM 8GB Samsung, dan storage NVMe SSD berkecepatan tinggi untuk menunjang aktivitas komputasi desktop.",
        background: "Tujuan pembuatan Mini PC ini adalah untuk menunjang aktivitas pengguna komputer desktop harian dengan konsumsi daya yang jauh lebih rendah dan efisien dibandingkan PC desktop x86 konvensional.",
        role: "Perakitan motherboard Orange Pi 5, pemasangan heatsink pendingin, konfigurasi arsitektur ARM dengan SoC RockChip RK3588S (8nm), integrasi chip RAM Samsung 8GB (dapat diekspansi hingga 32GB), serta instalasi storage NVMe SSD berkecepatan sangat cepat.",
        outcome: "Mini PC hemat daya berhasil dioperasikan dengan stabil untuk komputasi harian. Arsitektur ARM 8nm menghasilkan efisiensi energi yang optimal dengan suhu terkendali, serta kecepatan baca-tulis file yang sangat responsif berkat storage NVMe SSD.",
        image: "/assets/orangepi-lab.jpg",
        images: [
          { src: "/assets/orangepi-lab.jpg", label: "Setup Workstation Lab & Box Packaging" },
          { src: "/assets/orangepi-minipc.png", label: "Perakitan Board, Heatsink & Port I/O" },
        ],
      },
      {
        id: "smart-doorlock-arduino",
        cat: "iot",
        title: "Smart IoT System Door Lock Berbasis Arduino",
        desc: "Prototipe sistem pengaman pintu otomatis pintar berbasis mikrokontroler Arduino yang mengintegrasikan sensor biometrik sidik jari, layar LCD 16x2 I2C, modul nirkabel, dan aktuator solenoid door lock 12V.",
        background: "Proyek ini dirancang untuk meningkatkan sistem keamanan akses pintu secara otomatis dan meminimalisir risiko pembobolan atau kehilangan kunci fisik dengan beralih ke autentikasi biometrik digital dan kontrol berbasis IoT.",
        role: "Perancangan skema rangkaian elektronik, penulisan program firmware pada Arduino Uno, integrasi modul optical fingerprint scanner, wiring modul relay 5V/12V untuk aktuasi pengunci solenoid, konfigurasi display LCD 16x2 I2C, serta perakitan prototipe fisik panel bodi pintu.",
        outcome: "Sistem pengaman pintu pintar berhasil membaca dan mencocokkan sidik jari dengan cepat dan presisi. Status verifikasi ditampilkan jelas pada layar LCD, dan aktuator solenoid lock membuka secara otomatis serta mengunci kembali dengan aman dan andal.",
        image: "/assets/smart-doorlock-active.jpg",
        images: [
          { src: "/assets/smart-doorlock-active.jpg", label: "Sensor Biometrik & LCD Aktif" },
          { src: "/assets/smart-doorlock-circuit.jpg", label: "Wiring Sirkuit Arduino, Relay & Solenoid Lock" },
          { src: "/assets/smart-doorlock-front.jpg", label: "Perspektif Mockup Pintu & Bodi Panel" },
        ],
      },
      {
        id: "apotek-berkat-figma",
        cat: "uiux",
        title: "Desain UI/UX Aplikasi Apotek Online 'Apotek Berkat' (Figma)",
        desc: "Perancangan antarmuka (UI) dan alur pengalaman pengguna (UX) komprehensif untuk aplikasi Apotek Online 'Apotek Berkat' berbasis mobile app (User) dan web management dashboard (Admin) di Figma.",
        background: "Dirancang untuk mendigitalisasi layanan farmasi dan konsultasi kesehatan, mempermudah pasien dalam mengakses chat dokter, pemesanan obat resep & umum, layanan ambulance, serta pengelolaan inventaris apotek terpadu.",
        role: "Penyusunan User Persona & User Journey, pembuatan Wireframe (Low-Fidelity), perancangan Design System & Style Guide, pembuatan High-Fidelity UI untuk 15+ modul User (Chat Dokter, Obat Umum, Asuransi, Pembelian, dll.), serta perancangan 11 modul Admin Dashboard (Dokter, Obat, Ambulance, Jadwal, Rekam Medis).",
        outcome: "Menghasilkan prototipe Figma interaktif dengan alur transaksi dan navigasi yang intuitif, tata letak visual clean & human-centered, serta dokumentasi screen flow menyeluruh untuk kesiapan implementasi tahap development.",
        image: "/assets/apotek-home.png",
        images: [
          { src: "/assets/apotek-home.png", label: "Tampilan Beranda Mobile App (User Dashboard)" },
          { src: "/assets/apotek-welcome.png", label: "Halaman Selamat Datang / Onboarding Screen" },
          { src: "/assets/apotek-figma-user.png", label: "Struktur Canvas Figma: User Flow & Wireframe" },
          { src: "/assets/apotek-figma-admin.png", label: "Struktur Canvas Figma: Admin Dashboard System" },
        ],
      },
      {
        id: "pos-market-system",
        cat: "web",
        title: "Pembuatan Website Aplikasi Point of Sale (POS) Market",
        desc: "Aplikasi sistem kasir dan manajemen penjualan retail berbasis web (CodeIgniter 4) yang dilengkapi fitur multi-role (Kasir, Admin, Owner), input scanner barcode, dual display customer screen, dan pelaporan keuangan real-time.",
        background: "Proyek ini dikembangkan untuk mendigitalisasi operasional kasir dan manajemen toko retail secara terpadu, mempercepat proses checkout belanja pelanggan, serta mengotomatisasi pencatatan arus kas dan stok barang agar terhindar dari selisih pembukuan manual.",
        role: "Pengembangan full-stack web menggunakan PHP CodeIgniter 4 dan MySQL: perancangan skema database relasional, antarmuka responsif role-based (Kasir, Administrator, Owner), integrasi pencarian & scanner barcode produk, sistem keranjang belanja dengan kalkulasi otomatis nominal bayar dan kembalian, fitur Layar Customer (Dual Display), dashboard analitik grafik penjualan bulanan & distribusi kategori (Chart.js), serta modul rekapitulasi Laporan Keuangan & Operasional dengan filter rentang tanggal, pencatatan retur customer, dan cetak laporan.",
        outcome: "Aplikasi POS Market berhasil diimplementasikan dan berjalan stabil pada environment server lokal (localhost:8080). Transaksi kasir dapat diselesaikan dalam hitungan detik dengan pemotongan stok otomatis, pemisahan hak akses multi-role terisolasi dengan aman, serta rekapitulasi laba kotor dan omzet tersaji secara akurat dan siap dicetak.",
        image: "/assets/pos-kasir.png",
        images: [
          { src: "/assets/pos-kasir.png", label: "Antarmuka Kasir Penjualan: Input Barcode, Keranjang & Layar Customer (Dual Display)" },
          { src: "/assets/pos-dashboard.png", label: "Dashboard Administrator: Analisis Penjualan Bulanan & Distribusi Kategori Produk" },
          { src: "/assets/pos-laporan.png", label: "Laporan Keuangan & Operasional: Rekap Transaksi, Estimasi Laba & Filter Periode" },
        ],
      },
      {
        id: "readonline-platform",
        cat: "web",
        title: "Platform E-Book & Toko Buku Digital 'Read Onl1ne'",
        desc: "Aplikasi web katalog e-book dan toko buku digital interaktif yang dilengkapi pencarian terpadu, filtering kategori buku, fitur keranjang belanja (cart), serta alur checkout pembayaran digital.",
        background: "Proyek ini dikembangkan untuk menyediakan wadah membaca dan belanja buku digital yang modern, responsif, dan mudah diakses dari berbagai perangkat dengan antarmuka yang bersih dan nyaman bagi pembaca.",
        role: "Perancangan UI/UX lengkap di Figma (User flow, screen baca, dan flow pembayaran QRIS/transfer), slicing web frontend responsif (HTML, CSS, JavaScript), integrasi katalog buku dinamis, search filter, fitur cart & checkout, serta deployment ke Netlify.",
        outcome: "Aplikasi web 'Read Onl1ne' berhasil dideploy secara live dan dapat diakses publik. Memiliki navigasi yang lancar, katalog e-book beraneka genre, serta alur transaksi yang ramah pengguna.",
        image: "/assets/readonline-home.png",
        link: "https://readonl1ne.netlify.app",
        images: [
          { src: "/assets/readonline-home.png", label: "Tampilan Beranda Landing Page & Rekomendasi" },
          { src: "/assets/readonline-catalog.png", label: "Katalog E-Book, Kategori & Fitur Keranjang Belanja" },
          { src: "/assets/readonline-figma.png", label: "Desain UI/UX Figma: Alur Pengguna & Sistem Pembayaran" },
        ],
      },
      {
        id: "mikrotik-winserver-2019",
        cat: "hardware",
        title: "Konfigurasi Jaringan MikroTik & Windows Server 2019",
        desc: "Implementasi infrastruktur jaringan terintegrasi menggunakan Router MikroTik dan sistem operasi Windows Server 2019, mencakup manajemen routing, firewall NAT, DHCP & DNS server, Active Directory, serta konfigurasi domain client-server.",
        background: "Dirancang sebagai solusi infrastruktur jaringan perusahaan dan institusi untuk sentralisasi otentikasi pengguna, manajemen keamanan perimeter jaringan, alokasi bandwidth terstruktur, serta keandalan layanan server lokal.",
        role: "Instalasi dan konfigurasi sistem operasi Windows Server 2019, konfigurasi routerboard MikroTik (IP addressing, routing, NAT, firewall filtering, bandwidth queue), setup Active Directory Domain Services (AD DS), DNS Server, DHCP Server, serta pengujian konektivitas client-server.",
        outcome: "Topologi jaringan client-server berhasil dibangun dan beroperasi dengan andal. Komunikasi antar-segmen jaringan berjalan lancar, manajemen otentikasi pengguna tersentralisasi via domain controller, dan seluruh dokumentasi implementasi disajikan dalam format video panduan teknis yang komprehensif.",
        image: "/assets/mikrotik-winserver.jpg",
        video: "https://www.youtube.com/watch?v=gQKmTIRGP3s&t=4567s",
        youtubeId: "gQKmTIRGP3s",
        youtubeStart: 4567,
        images: [
          { src: "/assets/mikrotik-winserver.jpg", label: "Video Dokumentasi: Jaringan MikroTik & Windows Server 2019" },
        ],
      },
      {
        id: "instalasi-jaringan-kelompok",
        cat: "hardware",
        title: "Proyek Instalasi & Perancangan Jaringan Komputer Berkelompok",
        desc: "Dokumentasi seri video pelaksanaan proyek instalasi infrastruktur jaringan komputer secara tim, meliputi perencanaan topologi jaringan, crimping & pengujian kabel UTP, instalasi switch & router, serta troubleshooting konektivitas LAN.",
        background: "Proyek kolaboratif ini dilaksanakan secara berkelompok untuk mempraktikkan langsung standar implementasi instalasi kabel jaringan, instalasi perangkat keras jaringan lokal (LAN), manajemen pembagian tugas teknis dalam tim, serta validasi integritas komunikasi data.",
        role: "Koordinasi pembagian tugas tim teknis, penarikan dan crimping kabel UTP RJ-45 (standar T568A/T568B), pengujian integritas kabel menggunakan LAN Tester, pemasangan ke patch panel & switch, konfigurasi subnetting IP, serta perekaman dan penyusunan video dokumentasi proses kerja.",
        outcome: "Seluruh segmen kabel dan koneksi workstation berhasil terpasang dan teruji dengan status koneksi 100% passthrough tanpa packet loss. Proyek tuntas didokumentasikan dalam playlist video beruntun yang merinci setiap tahapan perancangan hingga pengujian.",
        image: "/assets/instalasi-jaringan.jpg",
        video: "https://youtube.com/playlist?list=PLTi9Un6PsdHI&si=imPzXzOqezRiRaqW",
        playlistId: "PLTi9Un6PsdHI",
        youtubeId: "kC8dnaLwSrE",
        images: [
          { src: "/assets/instalasi-jaringan.jpg", label: "Playlist Video: Instalasi Jaringan Berkelompok" },
        ],
      },
      {
        id: "network-security-phishing",
        cat: "hardware",
        title: "Video Edukasi Network Security: Bahaya & Simulasi Serangan Phishing",
        desc: "Proyek video edukasi dan simulasi keamanan jaringan (Network Security) yang membedah anatomi kejahatan siber phishing, eksploitasi social engineering, ancaman pencurian akun dalam 5 detik, serta langkah mitigasi perlindungan data pribadi.",
        background: "Dibuat untuk tugas Ujian Tengah Semester (UTS) mata kuliah Network Security di Politeknik LP3I Jakarta (Kelompok 4: Mochammad Jiddan Armansyiah, Andika Saputra, Reihan Demasiras Callada) dengan tujuan membangun kesadaran siber (cyber security awareness) di kalangan pengguna internet terhadap bahaya manipulasi tautan palsu.",
        role: "Penyusunan naskah skenario edukatif, riset mekanisme serangan phishing & social engineering, produksi konten visual dan editing video (kombinasi penjelasan teknis dan meme agar menarik serta tidak membosankan), voiceover, serta perumusan panduan mitigasi keamanan akun (identifikasi URL palsu, 2FA, dan verifikasi keamanan).",
        outcome: "Video edukasi keamanan siber berhasil diproduksi dan dipublikasikan di YouTube. Menyajikan materi Network Security yang kompleks menjadi tayangan interaktif, komunikatif, dan mudah dipahami oleh masyarakat luas guna mencegah kebocoran kredensial akun.",
        image: "/assets/phishing-security.jpg",
        video: "https://www.youtube.com/watch?v=PP21GNsqLGs&t=3s",
        youtubeId: "PP21GNsqLGs",
        youtubeStart: 3,
        images: [
          { src: "/assets/phishing-security.jpg", label: "Video Dokumentasi: Edukasi & Simulasi Network Security (Phishing)" },
        ],
      },
    ],
  },
  achievements: {
    num: "07",
    title: "Sertifikasi Kompetensi",
    sub: "Pengakuan kompetensi profesi resmi dari Badan Nasional Sertifikasi Profesi (BNSP).",
    items: [
      {
        title: "Database Administrator",
        issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
        year: "2026",
      },
      {
        title: "Tenaga Operator Komputer",
        issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
        year: "2025",
      },
    ],
  },
  contact: {
    num: "08", title: "Terbuka untuk kolaborasi, peluang kerja, atau diskusi santai.",
    sub: "Terbuka untuk peran entry-level di bidang IT Support, Web Development, Administrasi Jaringan & Server, serta Teknisi Hardware atau sekadar berdiskusi santai seputar teknologi.",
    whatsappTitle: "Chat via WhatsApp",
    whatsappSub: "Cara tercepat menghubungi saya biasanya dibalas dalam sehari.",
    quickLabel: "Tulis pesan singkat (opsional)",
    quickPlaceholder: "Halo Jiddan, saya melihat portofoliomu dan…",
    send: "Buka WhatsApp",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    locationLabel: "Lokasi",
  },
  footer: {
    tagline: "Profesionalisme, integritas, dan solusi berbasis data dalam setiap proyek.",
    explore: "Jelajahi", connect: "Terhubung",
    rights: "© 2026 Mochammad Jiddan Armansyiah.",
    backTop: "Kembali ke atas",
  },
};

content.id = content;
content.en = content;
